stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - hugo --cacheDir /tmp/cache/
  only:
    - master

deploy_job:
  stage: deploy
  script:
    - sudo rsync -rv ./public/ /var/www/html/
    - sudo chown -R root:root /var/www/html/
  only:
    - master
