variables:
  GIT_STRATEGY: clone

stages:
  - build
  - deploy

build_job:
  stage: build
  script:
    - hugo --cacheDir $HOME/cache
  only:
    - master

deploy_job:
  stage: deploy
  script:
    - sudo cp public/* /var/www/html/
    - sudo chown -R root:root /var/www/html/
  only:
    - master
