stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - hugo
  only:
    - master

deploy_job:
  stage: deploy
  script:
    - sudo rsync -rv ./public/ /var/www/html/
    - sudo chown root:root /var/www/html/ -R
  only:
    - master
