job:
  script:
    - hugo --cacheDir $HOME/cache
    - sudo cp -R public/* /var/www/html/
    - sudo chown -R root:root /var/www/html/
  only:
    - production

job:
  script:
    - hugo --cacheDir $HOME/cache
  only:
    - master
